-- =====================================================================
-- Данные новых потоков из предложения v0.4: паспорта потоков, 28 шагов,
-- владельцы, помощники, KPI (owners.json). VS2 переименован в «дистрибьютор».
-- Повторный запуск безопасен: вставка только того, чего ещё нет.
-- =====================================================================
update public.vs_streams
   set name = 'Формировать клиентский спрос (дистрибьютор)', short_name = 'Спрос: дистрибьютор',
       change_log = jsonb_build_array(jsonb_build_object('t', to_char(now() at time zone 'Europe/Moscow','DD.MM.YYYY HH24:MI'),
                    'text', 'Поток разделён: этот — VS2D «Клиентский спрос (дистрибьютор)», новый — VS2C «Клиентский спрос (потребитель)»')) || change_log
 where id = 'VS2' and name = 'Формировать клиентский спрос';
update public.vs_users set label = 'Интегратор VS2D · PrimeGrowth' where id = 'vs2';

insert into public.vs_streams (id, code, origin, team, tier, name, short_name, trigger_text, output, flow_object, recipient, value, kpi, industry_functions, handoff, sort, change_log)
values ('VS2C', 'VS2C', 'v0.4', 'Предложение v0.4', 2, 'Формировать осознанный клиентский спрос (потребитель)', 'Спрос: потребитель', 'Поставлена задача по спросу на продукт или получен новый запрос, требующий подбора решения', 'Зафиксирован осознанный выбор: корзина передана в оформление, пауза или отказ', 'Клиентская задача → предложение → сравнение → выбор → корзина', 'Конечный клиент (потребитель)', 'Помогать конечному клиенту понять предложение и самостоятельно выбрать подходящее решение на основе проверенных сведений', array['Конверсия в заказ','Стоимость нового клиента','Доля актуального материала','Доля с подтверждённым пониманием']::text[], 'Маркетинг, ДПД, E-commerce, Claims, Customer Experience', 'Маркетинг → ДПД и партнёр → E-commerce → VS3', 25,
  jsonb_build_array(jsonb_build_object('t', to_char(now() at time zone 'Europe/Moscow','DD.MM.YYYY HH24:MI'), 'text', 'Поток добавлен из предложения v0.4: шаги, владельцы, помощники и KPI')))
on conflict (id) do nothing;
insert into public.vs_streams (id, code, origin, team, tier, name, short_name, trigger_text, output, flow_object, recipient, value, kpi, industry_functions, handoff, sort, change_log)
values ('VS6', 'VS6', 'v0.4', 'Предложение v0.4', 2, 'Сопровождать партнёрский бизнес', 'Партнёрский бизнес', 'Партнёр активен; поступило обращение; расчётный период; готовится изменение; программа или событие; сигнал о нарушении', 'Партнёр получил начисления с объяснением, своевременную информацию и ответы; программы и признание проведены по правилам; нарушения закрыты', 'Действующий партнёр → информация, начисления, признание → удержание и рост структуры', 'Действующие партнёры и лидеры', 'Давать действующим партнёрам рабочие инструменты, своевременную информацию, понятное вознаграждение, признание и поддержку, чтобы они удерживали клиентов и развивали структуру', array['Удовлетворённость партнёров','Срок решения обращений','Доля начислений без корректировок','Удержание квалификации лидерами','Своевременность информирования','Нарушения правил на 1000 партнёров']::text[], 'ДПД, РАО, E-commerce, Финансы, Мотивация и признание, Мероприятия, Юристы', 'VS5 (лидер) → ДПД → РАО и Финансы → сеть', 60,
  jsonb_build_array(jsonb_build_object('t', to_char(now() at time zone 'Europe/Moscow','DD.MM.YYYY HH24:MI'), 'text', 'Поток добавлен из предложения v0.4: шаги, владельцы, помощники и KPI')))
on conflict (id) do nothing;
insert into public.vs_streams (id, code, origin, team, tier, name, short_name, trigger_text, output, flow_object, recipient, value, kpi, industry_functions, handoff, sort, change_log)
values ('VS7', 'VS7', 'v0.4', 'Предложение v0.4', 1, 'Развивать бренд и доверие', 'Бренд', 'Утверждена бренд-стратегия на период, выходит новая версия стандартов, открывается рынок или поступил репутационный сигнал', 'Показатели здоровья бренда на рынках достигнуты; стандарты применяются во всех потоках; репутационные случаи отработаны', 'Бренд-стратегия → платформа и стандарты → кампании → здоровье бренда', 'Клиенты, кандидаты и партнёры на всех рынках', 'Делать Coral Club узнаваемым и заслуживающим доверия выбором для клиентов, кандидатов и партнёров; обеспечивать единый смысл и облик во всех точках контакта', array['Известность бренда','Доверие','Доля брендового поиска','Соответствие стандарту','Репутационные случаи']::text[], 'Маркетинг, PR, Реклама, Мероприятия, Claims, Юристы', 'Маркетинг → регионы → все потоки', 70,
  jsonb_build_array(jsonb_build_object('t', to_char(now() at time zone 'Europe/Moscow','DD.MM.YYYY HH24:MI'), 'text', 'Поток добавлен из предложения v0.4: шаги, владельцы, помощники и KPI')))
on conflict (id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.1', 'VS2C', 1, 'Определить аудиторию', 'Выделить клиентские задачи, ситуации, ограничения и каналы
Приёмка: Для каждого сегмента описаны задача и основание выделения', 'Приоритетные сегменты', false, true, false, '{}'::int[], 'Доля кампаний, адресованных утверждённым сегментам', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает список приоритетных сегментов и их задачи. Уровень: Центр; кампании — регионы и страны. Арбитр: CEO. Также участвуют (нет в справочнике): Маркетинговая аналитика и CDP.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.1', 'mkt', 'owner'), ('VS2C.1', 'cx', 'helper'), ('VS2C.1', 'distr', 'helper'), ('VS2C.1', 'ecom', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.2', 'VS2C', 2, 'Сформулировать предложение', 'Связать задачу клиента с продуктом, применением, условиями и ограничениями
Приёмка: Указаны цена, роль и ограничения; каждое заявление связано с проверенным основанием', 'Ценностное предложение для сегмента', false, true, false, '{}'::int[], 'Доля клиентов с подтверждённым пониманием предложения', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает ценностное предложение для каждого сегмента. Уровень: Центр; кампании — регионы и страны. Арбитр: CEO.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.2', 'mkt', 'owner'), ('VS2C.2', 'fmul869ss', 'helper'), ('VS2C.2', 'claims', 'helper'), ('VS2C.2', 'fin', 'helper'), ('VS2C.2', 'distr', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.3', 'VS2C', 3, 'Подготовить и проверить материалы', 'Создать локализованные материалы и сценарии; проверить заявления и требования
Приёмка: Зафиксированы результаты проверок, срок актуальности и основания заявлений', 'Материалы с версией, рынком и статусом допуска', false, true, false, array[13,38,40]::int[], 'Доля опубликованных материалов с актуальным допуском; срок проверки', '100% опубликованных материалов с допуском; проверка 3–5 рабочих дней', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Маркетинг публикует материал только со статусом одобрения. Уровень: Одобрение: ЕС и США — Claims; ЕАЭС — Сертификация и качество. Арбитр: CEO. Закрывает конфликты 13, 38 и 40: один одобряющий на рынок. Также участвуют (нет в справочнике): Content Hub, локальные команды.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.3', 'mkt', 'owner'), ('VS2C.3', 'adv', 'helper'), ('VS2C.3', 'claims', 'helper'), ('VS2C.3', 'cert', 'helper'), ('VS2C.3', 'legal', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.4', 'VS2C', 4, 'Подготовить каналы и привлечь внимание', 'Настроить точки контакта, аналитику и маршрутизацию; запустить коммуникации
Приёмка: Пройден тест ссылок, форм и маршрута; каждое предложение связано с допущенным продуктом', 'Работающие каналы с измеряемым охватом', false, true, false, '{}'::int[], 'Стоимость нового клиента', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает медиаплан и точки контакта. Уровень: Центр; кампании — регионы и страны. Арбитр: CEO.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.4', 'mkt', 'owner'), ('VS2C.4', 'ecom', 'helper'), ('VS2C.4', 'adv', 'helper'), ('VS2C.4', 'pr', 'helper'), ('VS2C.4', 'event', 'helper'), ('VS2C.4', 'distr', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.5', 'VS2C', 5, 'Обеспечить следующий шаг для заинтересованного', 'Дать переход к самостоятельному выбору, цифровому подбору или разговору с партнёром
Приёмка: Проверен переход без заявки; для обращения указаны ответственный, срок и необходимый состав данных', 'Клиент перешёл к выбору; обращение получило ответственного', false, true, false, '{}'::int[], 'Доля обращений с первым ответом по существу в течение 24 часов', 'Ориентир для обсуждения — 90%', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает правила распределения обращений между партнёрами, срок ответа и порядок переназначения. Уровень: Центр — правила распределения; ответ — партнёры и ДПД стран. Арбитр: CEO. Основной путь заинтересованного клиента ведёт к партнёру.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.5', 'distr', 'owner'), ('VS2C.5', 'ecom', 'helper'), ('VS2C.5', 'cs', 'helper'), ('VS2C.5', 'rao', 'helper'), ('VS2C.5', 'mkt', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.6', 'VS2C', 6, 'Уточнить задачу и ограничения', 'Помочь определить ожидания, предпочтения и ограничения через материалы, цифровой или персональный подбор
Приёмка: В самостоятельном пути доступны критерии и ограничения; при подборе рекомендация содержит учтённые требования', 'Критерии выбора; при подборе — рекомендация с учётом задачи', false, true, false, '{}'::int[], 'Доля подборов с записанными ограничениями клиента', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Отвечает за стандарт партнёрской консультации и его соблюдение в сети. Уровень: Центр; кампании — регионы и страны. Арбитр: CEO. Партнёры независимы: компания владеет стандартом, инструментами и обучением.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.6', 'distr', 'owner'), ('VS2C.6', 'mkt', 'helper'), ('VS2C.6', 'ecom', 'helper'), ('VS2C.6', 'fmul869ss', 'helper'), ('VS2C.6', 'train', 'helper'), ('VS2C.6', 'claims', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.7', 'VS2C', 7, 'Помочь сравнить решения', 'Объяснить варианты, применение, ограничения и полную стоимость; проверить соответствие ожиданиям
Приёмка: В сравнении есть варианты, ограничения, применение и полная стоимость; доступны покупка, пауза и отказ', 'Сравнение вариантов и объяснение рекомендации', false, true, false, '{}'::int[], 'Доля консультаций с зафиксированным сравнением вариантов и полной стоимостью курса', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Отвечает за стандарт сравнения в партнёрском пути. Уровень: Центр; кампании — регионы и страны. Арбитр: CEO.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.7', 'distr', 'owner'), ('VS2C.7', 'mkt', 'helper'), ('VS2C.7', 'ecom', 'helper'), ('VS2C.7', 'train', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs2c_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS2C.8', 'VS2C', 8, 'Зафиксировать выбор и передать корзину', 'При согласии собрать корзину и передать в VS3; при паузе или отказе зафиксировать решение без навязывания
Приёмка: Для корзины определены состав, рынок и условия; причины отказа используются для улучшения', 'Согласованная корзина либо зафиксированная пауза или отказ', false, true, false, '{}'::int[], 'Конверсия корзины в оформленный заказ', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Отвечает за корзину и фиксацию паузы или отказа. Уровень: Центр; кампании — регионы и страны. Арбитр: CEO.')
on conflict (id) do nothing;
insert into public.vs2c_roles (step_id, function_id, role) values ('VS2C.8', 'ecom', 'owner'), ('VS2C.8', 'distr', 'helper'), ('VS2C.8', 'rao', 'helper'), ('VS2C.8', 'it', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.1', 'VS6', 1, 'Дать рабочий кабинет', 'Обеспечить партнёру доступ к структуре, объёмам, квалификациям, начислениям, материалам и истории обращений
Приёмка: Данные совпадают с расчётом периода; для каждого показателя указаны дата обновления и источник', 'Партнёр видит показатели и начисления без запроса', false, true, false, '{}'::int[], 'Обращения о начислениях и структуре на 1 000 активных партнёров', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Отвечает за кабинет партнёра и полноту данных в нём. Уровень: Центр — платформа; данные рынков — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.1', 'ecom', 'owner'), ('VS6.1', 'rao', 'helper'), ('VS6.1', 'it', 'helper'), ('VS6.1', 'distr', 'helper'), ('VS6.1', 'mkt', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.2', 'VS6', 2, 'Сообщать изменения до вступления в силу', 'Готовить сообщения об изменениях цен, маркетинг-плана, ассортимента, акций и доставки; сначала лидерам, затем сети
Приёмка: Сообщение содержит дату вступления, причину, влияние и ответы на частые вопросы; охват зафиксирован', 'Изменение доведено до активных партнёров до даты вступления', false, true, false, array[21]::int[], 'Доля активных партнёров, получивших сообщение об изменении до даты вступления', 'Все изменения цен и маркетинг-плана объявлены заранее; база — Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает календарь и канал сообщений для сети. Уровень: Центр — единая версия сообщения; доведение — регионы и лидеры. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Закрывает конфликт 21: информирование о рангах и Бонусе привилегий идёт одной версией из центра.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.2', 'distr', 'owner'), ('VS6.2', 'mkt', 'helper'), ('VS6.2', 'fin', 'helper'), ('VS6.2', 'rao', 'helper'), ('VS6.2', 'legal', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.3', 'VS6', 3, 'Решать обращения партнёров', 'Принимать вопросы о вознаграждении, структуре, спонсоре, статусе и учётной записи в отдельной очереди
Приёмка: Зафиксированы категория, ответственный, срок и ответ; повторные обращения по одной теме связаны (ветка: при обращении)', 'Обращение закрыто решением', false, true, false, '{}'::int[], 'Срок решения обращений партнёров', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Ведёт очередь обращений партнёров и сроки ответа. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.3', 'rao', 'owner'), ('VS6.3', 'distr', 'helper'), ('VS6.3', 'fin', 'helper'), ('VS6.3', 'it', 'helper'), ('VS6.3', 'cs', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.4', 'VS6', 4, 'Проверить и вознаградить результат', 'Рассчитать вознаграждение по маркетинг-плану, проверить основания, возвраты и корректировки
Приёмка: Начисление связано с расчётом; спорные начисления получили ответственного и срок пересмотра', 'Проверенный расчёт и начисление с объяснением', false, true, false, array[18,20,21,26]::int[], 'Доля начислений без корректировок после выплаты; срок разбора спорных начислений', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 30.10.2026. Полномочия: Считает вознаграждение по маркетинг-плану и отвечает за воспроизводимость. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Спор у автора: мировая практика разделяет расчёт и утверждение выплаты; альтернатива — передать расчёт Финансам (связано с D8). Конфликты 18, 20, 21, 26.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.4', 'rao', 'owner'), ('VS6.4', 'motiv', 'helper'), ('VS6.4', 'event', 'helper'), ('VS6.4', 'it', 'helper'), ('VS6.4', 'fin', 'claimant') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.5', 'VS6', 5, 'Проводить программы и признание', 'Запускать мотивационные программы и признание по утверждённым правилам: челленджи, признание квалификаций на событиях
Приёмка: Правила опубликованы до старта; итоги подведены в срок; критерии признания утверждены до события', 'Программа проведена; итоги и награды выданы по правилам', false, true, false, array[18]::int[], 'Доля программ с правилами до старта и итогами в объявленный срок', '100% программ', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает правила программ и критерии признания до старта. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Закрывает конфликт 18: критерии признания утверждает мотивация, церемонию проводит ивент.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.5', 'motiv', 'owner'), ('VS6.5', 'distr', 'helper'), ('VS6.5', 'rao', 'helper'), ('VS6.5', 'event', 'helper'), ('VS6.5', 'fin', 'helper'), ('VS6.5', 'legal', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.6', 'VS6', 6, 'Проводить события сети', 'Планировать и проводить форумы, лидерские встречи и региональные события с целью, программой и разбором результатов
Приёмка: До события утверждены цель и измеримый показатель; разбор подготовлен в течение двух недель', 'Событие проведено; цель и результат зафиксированы', false, true, false, '{}'::int[], 'Доля событий с утверждённой целью и разбором в течение двух недель', '100% событий', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Отвечает за подготовку и проведение событий. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.6', 'event', 'owner'), ('VS6.6', 'distr', 'helper'), ('VS6.6', 'mkt', 'helper'), ('VS6.6', 'interp', 'helper'), ('VS6.6', 'fin', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.7', 'VS6', 7, 'Работать с лидерами', 'Вести регулярный контакт: план развития структуры, данные о воронке, лидерский совет, разбор споров между линиями
Приёмка: План пересматривается по графику; предложения совета получили ответ и решение; споры закрыты', 'У каждого лидера согласованный план и регулярный контакт', false, true, false, '{}'::int[], 'Удержание квалификации лидерами за 12 месяцев', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Ведёт план и контакт с лидерами, собирает лидерский совет. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Также участвуют (нет в справочнике): Маркетинговая аналитика и CDP.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.7', 'distr', 'owner'), ('VS6.7', 'train', 'helper'), ('VS6.7', 'motiv', 'helper'), ('VS6.7', 'rao', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.8', 'VS6', 8, 'Контролировать соблюдение правил', 'Отслеживать заявления о здоровье и доходе, публикации и соблюдение политики; применять порядок: предупреждение, санкция, апелляция
Приёмка: Зафиксированы источник, правило, решение и срок; доступна апелляция; повторные нарушения видны в истории (ветка: при сигнале)', 'Нарушение закрыто решением в установленный срок', false, true, false, '{}'::int[], 'Подтверждённые нарушения на 1 000 активных партнёров; срок закрытия', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает порядок «предупреждение — санкция — апелляция». Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Практика отрасли: в США саморегулятор DSSRC отслеживает заявления.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.8', 'legal', 'owner'), ('VS6.8', 'claims', 'helper'), ('VS6.8', 'distr', 'helper'), ('VS6.8', 'rao', 'helper'), ('VS6.8', 'mkt', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.9', 'VS6', 9, 'Собирать обратную связь сети', 'Проводить регулярный опрос партнёров, собирать предложения лидеров, группировать сигналы и передавать адресатам
Приёмка: Зафиксированы функция, подтверждение и статус рассмотрения; партнёрам сообщён итог по ключевым темам', 'Сигналы сети приняты адресатами', false, true, false, '{}'::int[], 'Удовлетворённость партнёров по уровням', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Проводит опрос партнёров и собирает предложения лидеров. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Также участвуют (нет в справочнике): Маркетинговая аналитика и CDP.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.9', 'distr', 'owner'), ('VS6.9', 'cx', 'helper'), ('VS6.9', 'mkt', 'helper'), ('VS6.9', 'fmul869ss', 'helper'), ('VS6.9', 'rao', 'helper'), ('VS6.9', 'train', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.10', 'VS6', 10, 'Пересмотреть участие', 'При снижении активности выяснить причины и предложить поддержку; по решению оформить паузу или завершение
Приёмка: Решение зафиксировано; при выходе согласованы расчёты, доступы и передача клиентов (ветка: по запросу или сигналу)', 'План продолжения или корректно завершённое сотрудничество', false, true, false, '{}'::int[], 'Удержание активных партнёров за 90/180 дней', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Отвечает за удержание, паузу и корректный выход. Уровень: Центр — стандарт; работа с партнёрами — страны. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Кодексы DSA и WFDSA: обратный выкуп товара в товарном виде не ниже 90% стоимости.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.10', 'distr', 'owner'), ('VS6.10', 'rao', 'helper'), ('VS6.10', 'legal', 'helper'), ('VS6.10', 'fin', 'helper'), ('VS6.10', 'cx', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs6_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS6.11', 'VS6', 11, 'Пересматривать маркетинг-план и программы', 'Раз в год и при существенных изменениях оценивать экономику, поведение сети, практику рынка и регуляторные требования
Приёмка: Изменение прошло финансовую и юридическую проверку, утверждено и доведено до сети до вступления в силу', 'Решение по маркетинг-плану с оценкой влияния на доход и маржу', false, true, false, '{}'::int[], 'Доля вознаграждения, связанного с покупками клиентов', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 30.10.2026. Полномочия: Готовит изменения маркетинг-плана и программ; утверждают CEO и совет директоров. Уровень: Центр; утверждение — CEO и совет директоров. Арбитр: руководитель ДПД; спор с его функцией или между потоками — CEO. Спор у автора: владелец — открытое решение D10.')
on conflict (id) do nothing;
insert into public.vs6_roles (step_id, function_id, role) values ('VS6.11', 'distr', 'owner'), ('VS6.11', 'rao', 'helper'), ('VS6.11', 'fin', 'helper'), ('VS6.11', 'legal', 'helper'), ('VS6.11', 'mkt', 'helper'), ('VS6.11', 'fmul58rvd', 'helper'), ('VS6.11', 'fmul58ja4', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.1', 'VS7', 1, 'Измерить здоровье бренда', 'Проводить регулярный замер известности, доверия, ассоциаций и доли брендового поиска
Приёмка: Для каждого замера указаны выборка, период и сравнение с прошлым', 'Карта разрывов бренда по рынкам', false, true, false, '{}'::int[], 'Спонтанная и подсказанная известность в целевой аудитории', 'После первого замера по рынкам', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает методику замера и календарь. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): Маркетинговая аналитика, региональные команды.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.1', 'mkt', 'owner') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.2', 'VS7', 2, 'Утвердить платформу и архитектуру бренда', 'Определить смысл и обещание, манифест, роль основного бренда и суббрендов, правила имён
Приёмка: Версия утверждена уполномоченным участником; изменения и причины зафиксированы', 'Утверждённая версия платформы и архитектуры', false, true, false, '{}'::int[], 'Срок доведения новой версии платформы до всех потоков', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Готовит платформу и архитектуру бренда; утверждает CEO. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.2', 'mkt', 'owner'), ('VS7.2', 'fmukzxq2b', 'helper'), ('VS7.2', 'legal', 'helper'), ('VS7.2', 'fmul58rvd', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.3', 'VS7', 3, 'Выпустить стандарты бренда', 'Готовить стандарты стиля, языка и оформления точек контакта, включая правила для партнёров
Приёмка: Есть версия, дата, примеры и ответственный; потоки получили уведомление', 'Стандарты опубликованы в «Управлении знаниями» с версией', false, true, false, '{}'::int[], 'Соответствие стандарту по аудиту точек контакта', 'После первого аудита', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Публикует стандарты и отвечает на вопросы по применению. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): Дизайн.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.3', 'mkt', 'owner'), ('VS7.3', 'claims', 'helper'), ('VS7.3', 'train', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.4', 'VS7', 4, 'Спланировать брендовые коммуникации', 'Составить план по рынкам с отдельной строкой бюджета и показателями здоровья бренда
Приёмка: Бюджет учтён отдельно; для каждой активности указаны рынок, цель и показатель', 'Утверждённый план и бюджет бренда', false, true, false, '{}'::int[], 'Доля активностей бренда с назначенным показателем здоровья', '100% активностей', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Готовит план брендовых коммуникаций; утверждает CEO. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): региональные команды.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.4', 'mkt', 'owner'), ('VS7.4', 'fin', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.5', 'VS7', 5, 'Создать брендовые материалы и кампании', 'Производить видео, кампании, контент и события; проверять заявления до публикации
Приёмка: Зафиксированы проверка заявлений, соответствие стандарту и рынки применения', 'Одобренные материалы и запущенные кампании', false, true, false, '{}'::int[], 'Прирост известности после кампании на рынках кампании', 'После первого замера', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Утверждает брендовые материалы и кампании в пределах плана. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.5', 'mkt', 'owner'), ('VS7.5', 'adv', 'helper'), ('VS7.5', 'pr', 'helper'), ('VS7.5', 'event', 'helper'), ('VS7.5', 'claims', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.6', 'VS7', 6, 'Вывести бренд на рынки', 'Передать регионам материалы и обучение, адаптировать под рынок, оформить точки контакта
Приёмка: Региональная команда обучена; аудит точек проведён; отклонения внесены в план', 'Рынок работает по стандарту бренда', false, true, false, '{}'::int[], 'Доля рынков, прошедших аудит по стандарту бренда', 'После первого аудита', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Передаёт регионам материалы и обучение; принимает отчёт. Уровень: Центр — материалы и обучение; внедрение — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): региональные офисы.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.6', 'mkt', 'owner'), ('VS7.6', 'train', 'helper'), ('VS7.6', 'markets', 'helper'), ('VS7.6', 'distr', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.7', 'VS7', 7, 'Дать партнёрам брендовые материалы', 'Вести библиотеку готового контента и шаблонов; публиковать правила личного бренда партнёра
Приёмка: Библиотека обновляется по графику; у материалов указаны рынки и срок; использование отслеживается', 'Партнёры используют актуальные материалы', false, true, false, '{}'::int[], 'Доля активных партнёров, использующих материалы за месяц', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Ведёт библиотеку материалов и правила личного бренда. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): Content Hub.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.7', 'mkt', 'owner'), ('VS7.7', 'distr', 'helper'), ('VS7.7', 'claims', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.8', 'VS7', 8, 'Управлять репутацией', 'Вести отношения со СМИ, отслеживать упоминания, готовить позицию компании по инцидентам
Приёмка: Зафиксированы источник, позиция, согласования и срок реакции; итог разобран', 'Репутационный случай отработан по регламенту', false, true, false, '{}'::int[], 'Срок первой реакции на репутационный случай', 'После замера базы в Q4 2026', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Ведёт отношения со СМИ; готовит позицию по инцидентам. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): корпоративные коммуникации.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.8', 'pr', 'owner'), ('VS7.8', 'legal', 'helper'), ('VS7.8', 'cert', 'helper'), ('VS7.8', 'mkt', 'helper') on conflict (step_id, function_id) do nothing;
insert into public.vs7_steps (id, stream_id, position, name, content, result, is_custom, active, members_confirmed, hot_points, owner_metric, metric_target, note)
values ('VS7.9', 'VS7', 9, 'Оценить эффект и скорректировать', 'Сравнивать результаты с планом по показателям и корректировать план
Приёмка: Зафиксированы причины и ответственные; назначен следующий замер', 'Решения по корректировке плана бренда', false, true, false, '{}'::int[], 'Выполнение плановых показателей здоровья бренда', 'После первого цикла', 'Предложение v0.4 (черновик), пересмотр до 15.12.2026. Полномочия: Корректирует план в пределах бюджета. Уровень: Центр — платформа и стандарты; адаптация — регионы. Арбитр: директор по маркетингу; спор — CEO. Также участвуют (нет в справочнике): Маркетинговая аналитика и CDP.')
on conflict (id) do nothing;
insert into public.vs7_roles (step_id, function_id, role) values ('VS7.9', 'mkt', 'owner'), ('VS7.9', 'fin', 'helper') on conflict (step_id, function_id) do nothing;
